@hostname = http://localhost
@port = 3001
@host = {{hostname}}:{{port}}

###

GET {{host}}/api/biblioteclas/646f9921e2ba66f9e6e8aaab/salas

###

POST {{host}}/api/biblioteclas/salas
Content-Type: application/json
# x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY4MzQ3MjE3Nn0.Hj2gsIrhczza9SwPSnN9SmtqbWA6u1wynV1RzqibAyo

{
    "nombre": "Readers",
    "tipo": "Lectura"
}
